<?php

/**
 * @file
 * Contains accounts.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_help().
 */
function accounts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the accounts module.
    case 'help.page.accounts':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides custom entity to store information about accounts (companies) coming from crelate.com') . '</p>';
      return $output;

    default:
  }
}